name: C/C++ CI

on:
  push:
    branches: [ Luecx-patch-1 ]
  pull_request:
    branches: [ Luecx-patch-1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: make
#       working-directory: ./src_files/
#       run: 
#         make EXE=../bin/Koivisto
#     - name: run bench
#       working-directory: ./bin/
#       run: ./Koivisto bench
    - name: get bench from commit message
      run:
        echo ${{ github.event.head_commit.message }}
        echo ${{ github.event.commits[0].message }}
